const { sql } = require('@vercel/postgres');
const bcrypt = require('bcryptjs');

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
      res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
        if (req.method === 'OPTIONS') return res.status(200).end();

          const secret = req.headers['x-migrate-secret'] || req.query.secret;
            if (secret !== process.env.MIGRATE_SECRET) {
                return res.status(403).json({ error: 'Forbidden' });
                  }

                    try {
                        // Create tables
                            await sql`CREATE TABLE IF NOT EXISTS users (
                                  id SERIAL PRIMARY KEY,
                                        email VARCHAR(255) UNIQUE NOT NULL,
                                              password_hash VARCHAR(255) NOT NULL,
                                                    display_name VARCHAR(100) NOT NULL,
                                                          role VARCHAR(20) DEFAULT 'member',
                                                                city VARCHAR(100),
                                                                      bio TEXT DEFAULT '',
                                                                            created_at TIMESTAMP DEFAULT NOW(),
                                                                                  updated_at TIMESTAMP DEFAULT NOW()
                                                                                      )`;

                                                                                          await sql`CREATE TABLE IF NOT EXISTS posts (
                                                                                                id SERIAL PRIMARY KEY,
                                                                                                      user_id INTEGER REFERENCES users(id),
                                                                                                            title VARCHAR(255) NOT NULL,
                                                                                                                  body TEXT NOT NULL,
                                                                                                                        category VARCHAR(50) DEFAULT 'general',
                                                                                                                              city VARCHAR(100),
                                                                                                                                    likes INTEGER DEFAULT 0,
                                                                                                                                          created_at TIMESTAMP DEFAULT NOW()
                                                                                                                                              )`;
                                                                                                                                              
                                                                                                                                                  await sql`CREATE TABLE IF NOT EXISTS replies (
                                                                                                                                                        id SERIAL PRIMARY KEY,
                                                                                                                                                              post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
                                                                                                                                                                    user_id INTEGER REFERENCES users(id),
                                                                                                                                                                          body TEXT NOT NULL,
                                                                                                                                                                                created_at TIMESTAMP DEFAULT NOW()
                                                                                                                                                                                    )`;
                                                                                                                                                                                    
                                                                                                                                                                                        await sql`CREATE TABLE IF NOT EXISTS alerts (
                                                                                                                                                                                              id SERIAL PRIMARY KEY,
                                                                                                                                                                                                    user_id INTEGER REFERENCES users(id),
                                                                                                                                                                                                          title VARCHAR(255) NOT NULL,
                                                                                                                                                                                                                description TEXT,
                                                                                                                                                                                                                      type VARCHAR(50) DEFAULT 'general',
                                                                                                                                                                                                                            severity VARCHAR(20) DEFAULT 'low',
                                                                                                                                                                                                                                  city VARCHAR(100),
                                                                                                                                                                                                                                        lat DECIMAL(10,7),
                                                                                                                                                                                                                                              lng DECIMAL(10,7),
                                                                                                                                                                                                                                                    active BOOLEAN DEFAULT true,
                                                                                                                                                                                                                                                          created_at TIMESTAMP DEFAULT NOW()
                                                                                                                                                                                                                                                              )`;
                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                  await sql`CREATE TABLE IF NOT EXISTS city_votes (
                                                                                                                                                                                                                                                                        id SERIAL PRIMARY KEY,
                                                                                                                                                                                                                                                                              city VARCHAR(100) UNIQUE NOT NULL,
                                                                                                                                                                                                                                                                                    state VARCHAR(50),
                                                                                                                                                                                                                                                                                          votes INTEGER DEFAULT 0
                                                                                                                                                                                                                                                                                              )`;
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                  await sql`CREATE TABLE IF NOT EXISTS user_city_votes (
                                                                                                                                                                                                                                                                                                        id SERIAL PRIMARY KEY,
                                                                                                                                                                                                                                                                                                              user_id INTEGER REFERENCES users(id),
                                                                                                                                                                                                                                                                                                                    city_vote_id INTEGER REFERENCES city_votes(id),
                                                                                                                                                                                                                                                                                                                          created_at TIMESTAMP DEFAULT NOW(),
                                                                                                                                                                                                                                                                                                                                UNIQUE(user_id, city_vote_id)
                                                                                                                                                                                                                                                                                                                                    )`;
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                        // Seed data if requested
                                                                                                                                                                                                                                                                                                                                            if (req.query.seed === 'true') {
                                                                                                                                                                                                                                                                                                                                                  const adminHash = await bcrypt.hash('SafeTea2026!', 10);
                                                                                                                                                                                                                                                                                                                                                        const testHash = await bcrypt.hash('TestPass123!', 10);
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                              // Admin user
                                                                                                                                                                                                                                                                                                                                                                    await sql`INSERT INTO users (email, password_hash, display_name, role, city)
                                                                                                                                                                                                                                                                                                                                                                            VALUES ('admin@getsafetea.app', ${adminHash}, 'SafeTea Admin', 'admin', 'Austin')
                                                                                                                                                                                                                                                                                                                                                                                    ON CONFLICT (email) DO NOTHING`;
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                          // Test members
                                                                                                                                                                                                                                                                                                                                                                                                const testUsers = [
                                                                                                                                                                                                                                                                                                                                                                                                        ['kate@test.com', 'Kate M.', 'member', 'Austin'],
                                                                                                                                                                                                                                                                                                                                                                                                                ['jen@test.com', 'Jen R.', 'member', 'Denver'],
                                                                                                                                                                                                                                                                                                                                                                                                                        ['anna@test.com', 'Anna S.', 'moderator', 'Portland'],
                                                                                                                                                                                                                                                                                                                                                                                                                                ['lisa@test.com', 'Lisa K.', 'member', 'Seattle']
                                                                                                                                                                                                                                                                                                                                                                                                                                      ];
                                                                                                                                                                                                                                                                                                                                                                                                                                            for (const [email, name, role, city] of testUsers) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    await sql`INSERT INTO users (email, password_hash, display_name, role, city)
                                                                                                                                                                                                                                                                                                                                                                                                                                                              VALUES (${email}, ${testHash}, ${name}, ${role}, ${city})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ON CONFLICT (email) DO NOTHING`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Sample posts
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const posts = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ['Sketchy encounter at Zilker Park', 'Was walking alone near the south trail around 8pm and noticed someone following me for about 10 minutes. Stayed in well-lit areas and they eventually left. Stay aware out there!', 'safety-tip', 'Austin'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ['Best self-defense classes in Denver?', 'Looking for recommendations for women-focused self-defense classes in the Denver metro area. Prefer weekend classes!', 'recommendation', 'Denver'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ['New streetlights installed on Pearl St!', 'Great news - the city finally installed new LED streetlights along Pearl St between 5th and 12th. Feels so much safer walking home now.', 'good-news', 'Portland']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              for (const [title, body, category, city] of posts) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await sql`INSERT INTO posts (user_id, title, body, category, city)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SELECT id, ${title}, ${body}, ${category}, ${city}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          FROM users WHERE city = ${city} LIMIT 1`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Sample alerts
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const alerts = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ['Street Harassment Reported', 'Multiple reports of verbal harassment near 6th St bars area between 10pm-2am', 'harassment', 'medium', 'Austin'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ['Suspicious Activity', 'Reports of someone photographing women without consent at City Park', 'suspicious', 'high', 'Denver'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ['Well-Lit Safe Route Added', 'New safe walking route mapped from Union Station to Capitol Hill', 'safe-route', 'low', 'Denver']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (const [title, desc, type, severity, city] of alerts) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await sql`INSERT INTO alerts (user_id, title, description, type, severity, city)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  SELECT id, ${title}, ${desc}, ${type}, ${severity}, ${city}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FROM users WHERE role = 'admin' LIMIT 1`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // City votes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const cities = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ['Austin', 'TX', 127], ['Denver', 'CO', 98], ['Portland', 'OR', 85],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ['Seattle', 'WA', 76], ['Nashville', 'TN', 64], ['Atlanta', 'GA', 58]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          for (const [city, state, votes] of cities) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await sql`INSERT INTO city_votes (city, state, votes)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            VALUES (${city}, ${state}, ${votes})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ON CONFLICT (city) DO NOTHING`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.status(200).json({ success: true, message: 'Migration complete' + (req.query.seed === 'true' ? ' with seed data' : '') });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.error('Migration error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return res.status(500).json({ error: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
